version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-prototype-prod
    restart: always
    environment:
      POSTGRES_USER: prototype_prod
      POSTGRES_PASSWORD: prototype
      POSTGRES_DB: prototype_prod
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    container_name: prototype-app-prod
    restart: always
    depends_on:
      - db
    ports:
      - "8080:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL_PROD}
      SESSION_SECRET: ${SESSION_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    command: sh -c "
      npx prisma migrate deploy && \
      psql ${DATABASE_URL} -f ./db/seed.sql && \
      node index.js"

volumes:
  pgdata_prod:
    driver: local