name: Deploy app Homolog & Production

on:
  push:
    branches: [ homolog, main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm run test || true

      - name: Subir containers
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            sudo docker-compose -f docker-compose.prod.yml down
            sudo docker-compose -f docker-compose.prod.yml up -d --build
            npx prisma migrate deploy
          else
            sudo docker-compose -f docker-compose.hml.yml down
            sudo docker-compose -f docker-compose.hml.yml up -d --build
            npx prisma migrate deploy
          fi
