name: Deploy app Homolog & Production

on:
  push:
    branches: [ homolog, main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm run test || true

      - name: Subir containers
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build
            npx prisma migrate deploy
          else
            docker compose -f docker-compose.hml.yml down
            docker compose -f docker-compose.hml.yml up -d --build
            npx prisma migrate deploy
          fi
        env:
          DATABASE_URL_HML: ${{ secrets.DATABASE_URL_HML }}
          DATABASE_URL_PROD: ${{ secrets.DATABASE_URL_PROD }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
